// ==================== ENUMS ====================

export enum IncidentType {
  INJURY = 'INJURY',
  ILLNESS = 'ILLNESS',
  NEAR_MISS = 'NEAR_MISS',
  PROPERTY_DAMAGE = 'PROPERTY_DAMAGE',
  ENVIRONMENTAL = 'ENVIRONMENTAL',
}

export enum Severity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum IncidentStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  UNDER_INVESTIGATION = 'UNDER_INVESTIGATION',
  CLOSED = 'CLOSED',
}

export enum InvestigationStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  CLOSED = 'CLOSED',
}

export enum CAPAStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  VERIFIED = 'VERIFIED',
  OVERDUE = 'OVERDUE',
  CANCELLED = 'CANCELLED',
}

export enum Priority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum HazardCategory {
  MECHANICAL = 'MECHANICAL',
  ELECTRICAL = 'ELECTRICAL',
  CHEMICAL = 'CHEMICAL',
  BIOLOGICAL = 'BIOLOGICAL',
  ERGONOMIC = 'ERGONOMIC',
  PHYSICAL = 'PHYSICAL',
  ENVIRONMENTAL = 'ENVIRONMENTAL',
  BEHAVIORAL = 'BEHAVIORAL',
}

export enum RiskLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  EXTREME = 'EXTREME',
}

export enum AuditType {
  PPE_INSPECTION = 'PPE_INSPECTION',
  FIVE_S = 'FIVE_S',
  FIRE_SAFETY = 'FIRE_SAFETY',
  ELECTRICAL_SAFETY = 'ELECTRICAL_SAFETY',
  MACHINE_SAFETY = 'MACHINE_SAFETY',
  HOUSEKEEPING = 'HOUSEKEEPING',
  INTERNAL_AUDIT = 'INTERNAL_AUDIT',
  EXTERNAL_AUDIT = 'EXTERNAL_AUDIT',
  COMPLIANCE_CHECK = 'COMPLIANCE_CHECK',
}

export enum TrainingType {
  INDUCTION = 'INDUCTION',
  REFRESHER = 'REFRESHER',
  SKILL_BASED = 'SKILL_BASED',
  COMPLIANCE = 'COMPLIANCE',
  EMERGENCY_RESPONSE = 'EMERGENCY_RESPONSE',
  EQUIPMENT_OPERATION = 'EQUIPMENT_OPERATION',
}

export enum PPECategory {
  HEAD_PROTECTION = 'HEAD_PROTECTION',
  EYE_PROTECTION = 'EYE_PROTECTION',
  HEARING_PROTECTION = 'HEARING_PROTECTION',
  RESPIRATORY_PROTECTION = 'RESPIRATORY_PROTECTION',
  HAND_PROTECTION = 'HAND_PROTECTION',
  FOOT_PROTECTION = 'FOOT_PROTECTION',
  BODY_PROTECTION = 'BODY_PROTECTION',
  FALL_PROTECTION = 'FALL_PROTECTION',
  SAFETY_EQUIPMENT = 'SAFETY_EQUIPMENT',
}

export enum DrillType {
  FIRE_DRILL = 'FIRE_DRILL',
  EARTHQUAKE_DRILL = 'EARTHQUAKE_DRILL',
  CHEMICAL_SPILL = 'CHEMICAL_SPILL',
  MEDICAL_EMERGENCY = 'MEDICAL_EMERGENCY',
  EVACUATION = 'EVACUATION',
  LOCKDOWN = 'LOCKDOWN',
}

export enum NotificationType {
  INCIDENT_ASSIGNED = 'INCIDENT_ASSIGNED',
  INVESTIGATION_REQUIRED = 'INVESTIGATION_REQUIRED',
  CAPA_ASSIGNED = 'CAPA_ASSIGNED',
  CAPA_OVERDUE = 'CAPA_OVERDUE',
  TRAINING_SCHEDULED = 'TRAINING_SCHEDULED',
  CERTIFICATION_EXPIRING = 'CERTIFICATION_EXPIRING',
  AUDIT_SCHEDULED = 'AUDIT_SCHEDULED',
  DRILL_SCHEDULED = 'DRILL_SCHEDULED',
  HAZARD_REPORTED = 'HAZARD_REPORTED',
  APPROVAL_REQUIRED = 'APPROVAL_REQUIRED',
  SYSTEM_ALERT = 'SYSTEM_ALERT',
}
